### PR TITLE
Adding bootstrap.sh file

### LINKED ISSUE #7: FEAT: Configure Provisioning In The VM For Launching Django
#### Add a provisioning script, launched by the VM on its startup, that:
1. Installs *Pipenv* on the VM.
2. Installs the dependencies written in the *Pipenv*'s `Pipfile` / `Pipfile.lock` configuration files.
3. Launches *Django* application at `127.0.0.1:8000`.

> ATTENTION: This issue DEPENDS ON #6

### PR DESCRIPTION
**Pull request by DeanBiton**
- new file: bootstrap.sh
- Setup Vagrant to automatically bring our application up as well as
  make it accessible from a web browser

After running `vagrant up` the application can be accessed at:
> http://127.0.0.1:8000/

Depends on #3
Close #7

### CODE REVIEW

**Review by paOmer — APPROVED** [review]
LGTM

**Comment by taljacob2** [comment]
Looks great!
@DeanBiton please edit this PR's description, and mention it *"DEPENDS ON #3"* and that issue #7 may be closed,
by adding the lines:
```
DEPENDS ON #3
Close #7
```

**Comment by ShirleyFichman** [comment]
LGTM

**Review by ShirleyFichman — APPROVED** [review]
LGTM

**Review by Yarboa — CHANGES_REQUESTED** [review]
Sorry, as per the comment, you only add boostrap in the into the project
Why do you need all the extra files? 
The PRs that add vagrant file will deal with it.

I would recommend to have only the boostrap file in the PR

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
